export interface PoodleCut {
  slug: string
  name: string
  emoji: string
  difficulty: 'Easy' | 'Medium' | 'Advanced'
  maintenance: 'Low' | 'Low–Medium' | 'Medium' | 'Medium–High' | 'High' | 'Very High'
  frequency: string
  bestFor: string
  category: 'Popular' | 'Classic' | 'Show' | 'Warm Weather' | 'Cold Weather' | 'Trending' | 'Creative' | 'Practical'
  desc: string
  longDesc: string
  aiPrompt: string // prompt for FLUX Kontext
  shopLink: string
}

export const POODLE_CUTS: PoodleCut[] = [
  {
    slug: 'teddy-bear-cut',
    name: 'Teddy Bear Cut',
    emoji: '🧸',
    difficulty: 'Easy',
    maintenance: 'Low',
    frequency: 'Every 6–8 weeks',
    bestFor: 'Toy & miniature poodles',
    category: 'Popular',
    desc: 'Round, fluffy, irresistible. The most popular cut on Instagram.',
    longDesc: 'The Teddy Bear Cut features a rounded, plush face and uniform body length that makes your poodle look cuddly and adorable at any age. The hair around the face is trimmed into a circular shape, and the body is kept at an even 1–2 inch length. This cut is especially popular on social media for its instantly shareable cuteness.',
    aiPrompt: 'Give this poodle a teddy bear haircut: round fluffy face, soft circular shape around the muzzle and cheeks, uniform fluffy body coat about 1-2 inches long, rounded ears, plush and cuddly appearance. Keep the poodle\'s color and face shape exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=teddy-bear',
  },
  {
    slug: 'lamb-cut',
    name: 'Lamb Cut',
    emoji: '🐑',
    difficulty: 'Easy',
    maintenance: 'Low–Medium',
    frequency: 'Every 4–6 weeks',
    bestFor: 'All poodle sizes',
    category: 'Popular',
    desc: 'Even all over, slightly fuller legs. Natural and elegant.',
    longDesc: 'The Lamb Cut involves an even body trim with slightly fuller, more tapered legs — resembling the soft, rounded coat of a lamb. It\'s a natural-looking cut that\'s easy to maintain and works beautifully on all poodle sizes. The face is left clean and neat without being shaved down.',
    aiPrompt: 'Give this poodle a lamb cut: evenly trimmed body coat, slightly fuller and rounded legs, natural clean face, soft rounded silhouette throughout. Keep the poodle\'s color and basic features identical.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=lamb',
  },
  {
    slug: 'continental-cut',
    name: 'Continental Cut',
    emoji: '🏆',
    difficulty: 'Advanced',
    maintenance: 'High',
    frequency: 'Every 2–4 weeks',
    bestFor: 'Standard poodles, show dogs',
    category: 'Show',
    desc: 'The iconic show ring look. Dramatic, elegant, unforgettable.',
    longDesc: 'The Continental Cut is the most recognizable poodle haircut in the world — seen in dog shows and pop culture alike. It features shaved hindquarters, large pom-poms on the hips and ankles, a full fluffy chest and topknot, and a shaved face and feet. This is a high-maintenance show cut requiring professional grooming every 2–4 weeks.',
    aiPrompt: 'Give this poodle a continental show cut: shaved clean hindquarters and back legs, large round pom-poms on each ankle and hips, full fluffy chest and shoulders, elegant topknot on head, shaved face and feet, dramatic show dog appearance. Keep poodle\'s color exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=continental',
  },
  {
    slug: 'miami-cut',
    name: 'Miami / Bikini Cut',
    emoji: '🌴',
    difficulty: 'Easy',
    maintenance: 'Low',
    frequency: 'Every 6–8 weeks',
    bestFor: 'Active poodles, warm climates',
    category: 'Warm Weather',
    desc: 'Short body, chic pom-poms on ankles and tail.',
    longDesc: 'The Miami Cut — also called the Bikini Cut or Vlown Trim — keeps the body clipped very short while leaving stylish pom-poms of longer hair on the ankles, tail tip, and topknot. It\'s practical for warm weather, easy to maintain, and gives your poodle a playful, fashionable look.',
    aiPrompt: 'Give this poodle a Miami bikini cut: very short clipped body and legs, fluffy pom-poms on each ankle, fluffy pom-pom on tail tip, neat topknot, shaved face and feet. Playful and sporty appearance. Keep poodle\'s color identical.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=miami',
  },
  {
    slug: 'puppy-cut',
    name: 'Puppy Cut',
    emoji: '🐾',
    difficulty: 'Easy',
    maintenance: 'Low',
    frequency: 'Every 6–8 weeks',
    bestFor: 'All sizes, especially puppies',
    category: 'Popular',
    desc: 'Uniform 1–2 inch length all over. Classic, simple, always perfect.',
    longDesc: 'The Puppy Cut keeps hair at an even 1–2 inch length all over the body, giving adult poodles a youthful, fluffy appearance. It\'s the easiest cut to maintain, prevents matting, and looks great on poodles of any age. The AKC recognizes this as the standard trim for poodles under one year old.',
    aiPrompt: 'Give this poodle a puppy cut: uniform short fluffy coat about 1-2 inches long all over body, legs, and tail, slightly rounded face, neat and tidy youthful appearance. Keep poodle\'s color and face features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=puppy',
  },
  {
    slug: 'asian-fusion-cut',
    name: 'Asian Fusion Cut',
    emoji: '✨',
    difficulty: 'Medium',
    maintenance: 'Medium–High',
    frequency: 'Every 4–6 weeks',
    bestFor: 'Toy & miniature poodles',
    category: 'Trending',
    desc: 'Round teddy-bear head, shorter muzzle, sculpted ears. Most trendy cut of 2026.',
    longDesc: 'Inspired by Japanese grooming trends, the Asian Fusion Cut creates a doll-like appearance with an exaggerated round head, shorter clipped muzzle, and dramatically sculpted fluffy ears. The legs are often kept fuller for contrast with the shorter body. This creative, fashion-forward style is the fastest-growing trend on TikTok and Instagram.',
    aiPrompt: 'Give this poodle an Asian fusion grooming cut: perfectly round large fluffy head, shorter clipped muzzle area, dramatically sculpted fluffy rounded ears, shorter body coat, fuller fluffy legs, doll-like and adorable appearance. Keep poodle\'s color exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=asian-fusion',
  },
  {
    slug: 'summer-cut',
    name: 'Summer / Utility Cut',
    emoji: '☀️',
    difficulty: 'Easy',
    maintenance: 'Low',
    frequency: 'Every 8–10 weeks',
    bestFor: 'Active poodles, hot climates',
    category: 'Warm Weather',
    desc: 'Very short all over. Maximum comfort in heat, minimum maintenance.',
    longDesc: 'The Summer Cut — also called the Utility Cut — keeps the coat very short (around ½–1 inch) all over the body, helping poodles stay cool in hot weather. It\'s the most low-maintenance option available and is perfect for active dogs who swim or spend time outdoors. Regular sunscreen on exposed areas is recommended.',
    aiPrompt: 'Give this poodle a summer utility cut: very short clipped coat close to body all over, minimal but tidy appearance, clean and neat, practical short trim. Keep poodle\'s color and features identical.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=summer',
  },
  {
    slug: 'kennel-cut',
    name: 'Kennel Cut',
    emoji: '✂️',
    difficulty: 'Easy',
    maintenance: 'Low',
    frequency: 'Every 6–8 weeks',
    bestFor: 'All sizes, practical owners',
    category: 'Practical',
    desc: 'Short neck and face, classic topknot, easy upkeep.',
    longDesc: 'The Kennel Cut is a modified version of a show groom designed for easy day-to-day maintenance. It features a short body and legs, a classic topknot, an optional pom-pom tail, and a clean short face and neck. It maintains the recognizable poodle look without the intensive maintenance of show cuts.',
    aiPrompt: 'Give this poodle a kennel cut: short neat body and legs, clean short face and neck, rounded topknot on top of head, small fluffy pom-pom on tail tip. Classic tidy poodle appearance. Keep poodle\'s color and features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=kennel',
  },
  {
    slug: 'german-cut',
    name: 'German Cut',
    emoji: '🪮',
    difficulty: 'Medium',
    maintenance: 'Medium',
    frequency: 'Every 4–6 weeks',
    bestFor: 'Standard poodles',
    category: 'Classic',
    desc: 'Longer natural body coat, shorter face. Elegant and playful.',
    longDesc: 'The German Cut leaves the body coat longer than most pet cuts, creating a natural, flowing look, while the face is kept shorter and neater. Longer legs with a shaved face give this style a balanced, dignified appearance. It\'s a favorite for poodle owners who want something less traditional than show cuts but more polished than a puppy cut.',
    aiPrompt: 'Give this poodle a German cut: longer flowing body coat, shorter neatly clipped face, longer elegant legs, natural flowing appearance, dignified and refined look. Keep poodle\'s color and features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=german',
  },
  {
    slug: 'town-and-country-cut',
    name: 'Town & Country Cut',
    emoji: '🏡',
    difficulty: 'Medium',
    maintenance: 'Medium',
    frequency: 'Every 5–6 weeks',
    bestFor: 'Standard & miniature poodles',
    category: 'Classic',
    desc: 'Shorter body, longer scissored legs. Flashy and stylish.',
    longDesc: 'The Town & Country Cut features a shorter body with dramatically longer, scissored legs that create a flashy, show-pet appearance. The longer legs prevent the "stick leg" look common in shorter trims. A topknot and clean face complete the refined aesthetic.',
    aiPrompt: 'Give this poodle a town and country cut: shorter trimmed body, dramatically longer fluffy scissored legs, elegant topknot, clean face and neck, stylish pet trim. Keep poodle\'s color and features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=town-country',
  },
  {
    slug: 'english-saddle-cut',
    name: 'English Saddle Cut',
    emoji: '🎪',
    difficulty: 'Advanced',
    maintenance: 'High',
    frequency: 'Every 2–3 weeks',
    bestFor: 'Standard show poodles',
    category: 'Show',
    desc: 'Fuller hindquarters vs continental. Classic AKC show standard.',
    longDesc: 'The English Saddle Cut is one of the two AKC-accepted show clips for adult poodles. Unlike the Continental Cut, it retains more hair on the hindquarters, divided into a "saddle" pattern. It\'s slightly less dramatic than the Continental but equally demanding in terms of maintenance and professional grooming skill.',
    aiPrompt: 'Give this poodle an English saddle show cut: full chest and shoulders, curved saddle pattern of longer hair on hindquarters, pom-poms on ankles and knees, elegant topknot, shaved face. Show dog appearance. Keep poodle\'s color exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=english-saddle',
  },
  {
    slug: 'lion-cut',
    name: 'Lion Cut',
    emoji: '🦁',
    difficulty: 'Medium',
    maintenance: 'Medium',
    frequency: 'Every 5–6 weeks',
    bestFor: 'Standard poodles',
    category: 'Classic',
    desc: 'Full mane, shaved hindquarters. Bold and dramatic.',
    longDesc: 'The Lion Cut keeps a full, flowing mane around the chest and neck while shaving down the hindquarters. Optional pom-poms on the ankles complete the regal, lion-like silhouette. This historically influenced cut was practical for water-retrieving dogs and has come back into style for its dramatic appearance.',
    aiPrompt: 'Give this poodle a lion cut: full fluffy mane around chest and neck area, shaved hindquarters and back, optional small pom-poms on ankles, bold lion-like silhouette. Keep poodle\'s color and face features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=lion',
  },
  {
    slug: 'winter-cut',
    name: 'Winter Cut',
    emoji: '❄️',
    difficulty: 'Easy',
    maintenance: 'Low',
    frequency: 'Every 8–10 weeks',
    bestFor: 'Cold climates (Canada, northern US)',
    category: 'Cold Weather',
    desc: 'Longer coat for warmth. Perfect for cold US and Canadian winters.',
    longDesc: 'The Winter Cut simply leaves the coat longer all over to provide insulation during cold weather. It requires more frequent brushing to prevent matting but reduces grooming appointments. Ideal for poodles in cold climates like Canada and the northern US, it\'s practical and cozy.',
    aiPrompt: 'Give this poodle a winter cut: longer fluffy coat all over body and legs for warmth, full coat appearance, cozy and fluffy look. Keep poodle\'s color and features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=winter',
  },
  {
    slug: 'topknot-style',
    name: 'Topknot Style',
    emoji: '💎',
    difficulty: 'Medium',
    maintenance: 'Medium',
    frequency: 'Every 4–6 weeks',
    bestFor: 'Toy & miniature poodles',
    category: 'Trending',
    desc: 'Hair tied above the head for a chic, polished look.',
    longDesc: 'The Topknot Style involves gathering and tying the hair above the head into an elegant focal point, while keeping the rest of the coat at a neat, manageable length. It\'s ideal for formal occasions or photoshoots and can be combined with bows or accessories for extra flair.',
    aiPrompt: 'Give this poodle a topknot style: hair gathered and tied elegantly on top of head creating a high topknot, neat trimmed body and legs, polished formal appearance. Keep poodle\'s color and features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=topknot',
  },
  {
    slug: 'mohawk-cut',
    name: 'Mohawk / Rocker Cut',
    emoji: '🎸',
    difficulty: 'Medium',
    maintenance: 'Medium',
    frequency: 'Every 4–5 weeks',
    bestFor: 'Confident, adventurous owners',
    category: 'Creative',
    desc: 'Spiked ridge along the head and neck. Bold and full of personality.',
    longDesc: 'The Mohawk Cut spikes the hair along the top of the head and down the neck into a bold, edgy ridge. The body is kept shorter for contrast. It\'s a creative, conversation-starting cut that lets your poodle\'s personality shine through.',
    aiPrompt: 'Give this poodle a mohawk rocker cut: spiked ridge of hair along the top of head and down neck, shorter body coat, bold and edgy appearance. Keep poodle\'s color and face features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=mohawk',
  },
  {
    slug: 'minimalist-trim',
    name: 'Minimalist Face Trim',
    emoji: '🪴',
    difficulty: 'Easy',
    maintenance: 'Low',
    frequency: 'Every 8 weeks',
    bestFor: 'Busy owners, all sizes',
    category: 'Practical',
    desc: 'Moderate body length, sharp clean facial lines. Effortless chic.',
    longDesc: 'The Minimalist Face Trim keeps the overall coat at a moderate length while focusing on sharp, clean facial lines and a precisely groomed tail tip. It\'s the least time-intensive option that still maintains a polished look. Perfect for busy owners who want their poodle to look intentionally styled without intensive grooming.',
    aiPrompt: 'Give this poodle a minimalist trim: moderate length body coat, clean sharp facial lines, neat well-defined face, tidy tail, clean and intentional minimal grooming look. Keep poodle\'s color and features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=minimalist',
  },
  {
    slug: 'corded-coat',
    name: 'Corded Coat',
    emoji: '🎭',
    difficulty: 'Advanced',
    maintenance: 'Very High',
    frequency: 'Monthly specialist',
    bestFor: 'Dedicated show dog owners',
    category: 'Show',
    desc: 'Natural rope-like cords. Years to develop, striking result.',
    longDesc: 'The Corded Coat allows the poodle\'s naturally curly coat to mat into long, rope-like cords — similar to dreadlocks. It takes years to develop properly and requires specialist grooming knowledge. The result is one of the most visually striking and unique looks in the dog world, but it demands total commitment.',
    aiPrompt: 'Give this poodle a corded coat style: long rope-like natural cords hanging from body, distinctive dreadlock-like appearance, striking and unusual look. Keep poodle\'s color and features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=corded',
  },
  {
    slug: 'sporting-clip',
    name: 'Sporting Clip',
    emoji: '🏅',
    difficulty: 'Easy',
    maintenance: 'Low',
    frequency: 'Every 6–8 weeks',
    bestFor: 'Active poodles, athletic owners',
    category: 'Practical',
    desc: 'Uniform length, tail pom-pom. Simple, athletic, clean.',
    longDesc: 'The Sporting Clip is similar to the Puppy Cut but with one defining feature: a fluffy pom-pom on the tail tip. Uniform length all over, easy to maintain, and clean-looking. It\'s one of the AKC-accepted trims for adult show dogs in sporting events and is perfect for active poodles.',
    aiPrompt: 'Give this poodle a sporting clip: uniform short coat all over body and legs, single fluffy pom-pom on tail tip, clean face, athletic and tidy appearance. Keep poodle\'s color and features exactly the same.',
    shopLink: 'https://poodlesworld.com?utm_source=poodlehaircuts&utm_medium=cut&utm_campaign=sporting',
  },
]

export function getCutBySlug(slug: string): PoodleCut | undefined {
  return POODLE_CUTS.find(c => c.slug === slug)
}

export function getCutsByCategory(category: string): PoodleCut[] {
  if (category === 'All') return POODLE_CUTS
  return POODLE_CUTS.filter(c => c.category === category)
}
